--469 rekordow
-- Wstawianie produktów tylko jeśli tabela jest pusta
DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM food_products LIMIT 1) THEN
            INSERT INTO food_products (name, calories, protein, fat, carbs) VALUES
                                                                                ('Agrest', 41.0, 0.8, 0.2, 11.8),
                                                                                ('Amarantus, nasiona', 400.0, 14.5, 6.5, 66.2),
                                                                                ('Ananas', 54.0, 0.4, 0.2, 13.6),
                                                                                ('Ananas w syropie', 84.0, 0.4, 0.1, 21.0),
                                                                                ('Anyż', 337.0, 17.6, 16.0, 50.0),
                                                                                ('Arbuz', 36.0, 0.6, 0.1, 8.4),
                                                                                ('Avocado', 160.0, 2.0, 15.3, 7.4),
                                                                                ('Bakłażan', 21.0, 1.1, 0.1, 6.3),
                                                                                ('Baleron', 244.0, 15.1, 20.2, 0.9),
                                                                                ('Banan', 95.0, 1.0, 0.3, 23.5),
                                                                                ('Banany suszone', 360.0, 3.8, 1.1, 88.8),
                                                                                ('Bazylia suszona', 251.0, 14.3, 4.0, 61.0),
                                                                                ('Bazylia świeża', 23.0, 3.2, 0.6, 2.7),
                                                                                ('Biała rzodkiew', 14.0, 1.0, 0.0, 3.0),
                                                                                ('Białko jajka kurzego', 49.0, 10.9, 0.2, 0.7),
                                                                                ('Bób', 66.0, 7.1, 0.4, 14.0),
                                                                                ('Boćwina', 17.0, 2.1, 0.5, 5.5),
                                                                                ('Boczek wędzony', 477.0, 13.0, 47.0, 0.0),
                                                                                ('Botwinka', 17.0, 2.1, 0.5, 5.5),
                                                                                ('Brokuły', 27.0, 3.0, 0.4, 5.2),
                                                                                ('Brukselka', 37.0, 4.7, 0.5, 8.7),
                                                                                ('Brzoskwinia', 46.0, 1.0, 0.2, 11.9),
                                                                                ('Brzoskwinia w syropie', 73.0, 0.4, 0.1, 18.2),
                                                                                ('Bułka owsiana', 304.0, 9.3, 4.5, 58.4),
                                                                                ('Bułka pszenna zwykła', 273.0, 8.1, 1.5, 57.7),
                                                                                ('Bułka sojowa', 315.0, 10.1, 4.0, 61.1),
                                                                                ('Bułka tarta', 347.0, 9.7, 1.9, 77.6),
                                                                                ('Bułka wrocławskia', 294.0, 8.0, 4.4, 56.6),
                                                                                ('Burak', 38.0, 1.8, 0.1, 9.5),
                                                                                ('Cebula', 30.0, 1.4, 0.4, 6.9),
                                                                                ('Cebula czerwona', 30.0, 1.4, 0.4, 6.9),
                                                                                ('Cebula konserwowa', 52.0, 0.7, 0.2, 12.4),
                                                                                ('Cebulka dymka', 30.0, 1.4, 0.4, 6.9),
                                                                                ('Chili', 40.0, 0.4, 0.1, 1.8),
                                                                                ('Chleb chrupki', 353.0, 8.7, 2.4, 78.9),
                                                                                ('Chleb pszenny', 257.0, 8.5, 1.4, 54.3),
                                                                                ('Chleb zwykły', 248.0, 6.1, 1.3, 56.3),
                                                                                ('Chleb żytni pełnoziarnisty', 225.0, 6.8, 1.8, 53.8),
                                                                                ('Chleb żytni razowy', 213.0, 5.9, 1.7, 51.2),
                                                                                ('Chrzan', 67.0, 4.5, 0.6, 18.1),
                                                                                ('Ciecierzyca konserwowa', 127.0, 6.0, 3.0, 18.0),
                                                                                ('Cieciorka', 364.0, 19.3, 6.0, 60.6),
                                                                                ('Cielęcina łopatka', 106.0, 19.9, 2.8, 0.0),
                                                                                ('Cielęcina sznyclówka', 105.0, 20.5, 2.4, 0.0),
                                                                                ('Cielęcina udziec', 108.0, 19.9, 3.1, 0.0),
                                                                                ('Cukier', 405.0, 0.0, 0.0, 99.8),
                                                                                ('Cukier brązowy', 380.0, 0.1, 0.0, 98.0),
                                                                                ('Cukier puder', 387.0, 0.0, 0.0, 100.0),
                                                                                ('Cukinia', 15.0, 1.2, 0.1, 3.2),
                                                                                ('Curry', 325.0, 13.0, 14.0, 58.0),
                                                                                ('Ćwikła', 40.0, 1.6, 0.1, 10.2),
                                                                                ('Cykoria', 21.0, 1.7, 0.2, 4.1),
                                                                                ('Cynamon', 247.0, 4.0, 1.2, 81.0),
                                                                                ('Cytryna', 36.0, 0.8, 0.3, 9.5),
                                                                                ('Czekolada gorzka', 554.0, 6.7, 34.3, 56.6),
                                                                                ('Czereśnie', 61.0, 1.0, 0.3, 14.6),
                                                                                ('Czerwona fasola konserwowa', 87.0, 8.1, 0.6, 12.3),
                                                                                ('Czosnek', 146.0, 6.4, 0.5, 32.6),
                                                                                ('Czosnek granulowany', 331.0, 17.0, 0.7, 73.0),
                                                                                ('Daktyle suszone', 277.0, 2.0, 0.4, 74.0),
                                                                                ('Dorsz filety bez skóry', 70.0, 16.5, 0.3, 0.0),
                                                                                ('Dynia', 28.0, 1.3, 0.3, 7.7),
                                                                                ('Dżem jagodowy niskosłodzony', 153.0, 0.3, 0.2, 38.2),
                                                                                ('Dżem śliwkowy niskosłodzony', 153.0, 0.3, 0.1, 37.9),
                                                                                ('Dżem truskawkowy niskosłodzony', 153.0, 0.3, 0.2, 37.8),
                                                                                ('Dżem wiśniowy niskosłodzony', 154.0, 0.4, 0.2, 37.5),
                                                                                ('Ekstrakt z wanilii', 288.0, 0.0, 0.0, 14.0),
                                                                                ('Estragon', 295.0, 23.0, 7.2, 50.0),
                                                                                ('Fasola biała suche nasiona', 288.0, 21.4, 1.6, 61.6),
                                                                                ('Fasola cięta, konserwowa, bez zalewy', 16.0, 1.5, 0.2, 4.5),
                                                                                ('Fasola szparagowa', 27.0, 2.4, 0.2, 7.6),
                                                                                ('Fasolka szparagowa, mrożonka', 24.0, 2.2, 0.2, 6.8),
                                                                                ('Figi suszone', 290.0, 3.6, 1.2, 78.0),
                                                                                ('Filet z makreli w sosie pomidorowym', 150.0, 13.1, 9.0, 4.0),
                                                                                ('Flądra świeża', 83.0, 16.5, 1.8, 0.0),
                                                                                ('Gałka muszkatołowa', 475.0, 6.7, 32.0, 50.0),
                                                                                ('Goździk', 323.0, 6.0, 20.0, 61.0),
                                                                                ('Grahamka', 252.0, 9.0, 1.7, 56.1),
                                                                                ('Granat', 83.0, 1.7, 1.2, 18.7),
                                                                                ('Grejpfrut', 36.0, 0.6, 0.2, 9.8),
                                                                                ('Grejpfrut czerwony', 42.0, 0.8, 0.1, 10.7),
                                                                                ('Grejpfrut zielony', 36.0, 0.6, 0.2, 9.8),
                                                                                ('Groch suche nasiona', 293.0, 23.8, 1.4, 60.2),
                                                                                ('Groszek ptysiowy', 476.0, 14.9, 30.2, 37.6),
                                                                                ('Groszek zielony', 75.0, 6.7, 0.4, 17.0),
                                                                                ('Groszek zielony konserwowy', 63.0, 4.9, 0.2, 15.8),
                                                                                ('Gruszka', 54.0, 0.6, 0.2, 14.4),
                                                                                ('Grzyby suszone', 284.0, 9.3, 0.7, 73.0),
                                                                                ('Halibut świeży', 98.0, 20.1, 1.9, 0.0),
                                                                                ('Herbata bez cukru', 0.0, 0.1, 0.0, 0.0),
                                                                                ('Imbir', 347.0, 9.1, 6.0, 71.0),
                                                                                ('Jabłka suszone', 238.0, 2.1, 2.1, 62.3),
                                                                                ('Jabłko', 46.0, 0.4, 0.4, 12.1),
                                                                                ('Jagody', 45.0, 0.8, 0.6, 12.2),
                                                                                ('Jajko kurze', 139.0, 12.5, 9.7, 0.6),
                                                                                ('Jajko przepiórcze', 158.0, 13.0, 11.0, 0.4),
                                                                                ('Jarmuż', 29.0, 3.3, 0.7, 6.1),
                                                                                ('Jogurt naturalny 2%', 60.0, 4.3, 2.0, 6.2),
                                                                                ('Kabanos', 326.0, 27.4, 24.3, 0.0),
                                                                                ('Kabanos z kurczaka', 247.0, 22.8, 17.4, 0.1),
                                                                                ('Kajzerka', 296.0, 8.4, 3.6, 58.6),
                                                                                ('Kakao w proszku 16%', 448.0, 18.2, 21.7, 50.6),
                                                                                ('Kalafior', 22.0, 2.4, 0.2, 5.0),
                                                                                ('Kalarepa', 29.0, 2.2, 0.3, 6.5),
                                                                                ('Kapary', 23.0, 2.4, 0.9, 4.9),
                                                                                ('Kapusta biała', 29.0, 1.7, 0.2, 7.4),
                                                                                ('Kapusta czerwona', 27.0, 1.9, 0.2, 6.7),
                                                                                ('Kapusta kwaszona', 12.0, 1.1, 0.2, 3.4),
                                                                                ('Kapusta pekińska', 12.0, 1.2, 0.2, 3.2),
                                                                                ('Kapusta włoska', 38.0, 3.3, 0.4, 7.8),
                                                                                ('Kardamon', 311.0, 11.0, 6.7, 68.0),
                                                                                ('Karp świeży', 110.0, 18.0, 4.2, 0.0),
                                                                                ('Kasza gryczana', 336.0, 12.6, 3.1, 69.3),
                                                                                ('Kasza jaglana', 346.0, 10.5, 2.9, 71.6),
                                                                                ('Kasza jęczmienna pęczak', 334.0, 8.4, 2.0, 74.9),
                                                                                ('Kasza jęczmienna perłowa', 327.0, 6.9, 2.2, 75.0),
                                                                                ('Kasza kukurydziana', 337.0, 8.0, 1.7, 72.0),
                                                                                ('Kasza manna', 348.0, 8.7, 1.3, 76.7),
                                                                                ('Kaszanka jęczmienna', 195.0, 8.5, 12.6, 13.0),
                                                                                ('Kawa bez cukru', 2.0, 0.2, 0.0, 0.3),
                                                                                ('Keczup', 93.0, 1.8, 1.0, 22.2),
                                                                                ('Kefir 2%', 51.0, 3.4, 2.0, 4.7),
                                                                                ('Kefir 2% z wapniem', 51.0, 3.4, 2.0, 4.7),
                                                                                ('Kiełbasa delikatesowa z kurczaka', 109.0, 19.6, 3.3, 0.1),
                                                                                ('Kiełbasa domowa', 320.0, 14.7, 29.2, 0.5),
                                                                                ('Kiełbasa jałowcowa z kurczaka', 236.0, 19.0, 17.9, 0.1),
                                                                                ('Kiełbasa kanapkowa z kurczaka', 179.0, 11.8, 13.5, 3.0),
                                                                                ('Kiełbasa lubuska', 249.0, 17.5, 18.0, 4.8),
                                                                                ('Kiełbasa parówkowa', 323.0, 11.0, 31.5, 0.0),
                                                                                ('Kiełbasa podlaska z kurczaka', 232.0, 20.7, 16.7, 0.1),
                                                                                ('Kiełbasa podsuszana z kurczaka', 162.0, 21.7, 8.4, 0.0),
                                                                                ('Kiełbasa podwawelska', 247.0, 17.3, 19.6, 0.9),
                                                                                ('Kiełbasa rzeszowska', 203.0, 20.9, 13.4, 0.0),
                                                                                ('Kiełbasa śląska', 210.0, 18.4, 15.3, 0.0),
                                                                                ('Kiełbasa sucha krakowska', 323.0, 25.6, 24.8, 0.0),
                                                                                ('Kiełbasa sucha myśliwska', 291.0, 27.8, 20.1, 0.0),
                                                                                ('Kiełbasa szynkowa z kurczaka', 110.0, 16.2, 5.0, 0.0),
                                                                                ('Kiełbasa toruńska', 263.0, 20.9, 20.1, 0.0),
                                                                                ('Kiełbasa zwyczajna', 209.0, 17.6, 15.6, 0.0),
                                                                                ('Kiełbasa żywiecka', 315.0, 20.3, 26.3, 0.0),
                                                                                ('Kiełbaski bawarskie', 308.0, 15.5, 27.7, 0.1),
                                                                                ('Kiełki bambusa', 20.0, 1.1, 0.6, 2.0),
                                                                                ('Kiełki brokuła', 57.0, 5.0, 0.0, 6.8),
                                                                                ('Kiełki buraka', 37.0, 1.6, 0.2, 9.6),
                                                                                ('Kiełki fasoli mung', 29.0, 3.0, 0.4, 6.2),
                                                                                ('Kiełki lucerny', 23.0, 4.0, 0.7, 2.1),
                                                                                ('Kiełki rzodkiewki', 43.0, 3.8, 2.5, 3.6),
                                                                                ('Kiełki słonecznika', 31.0, 3.4, 0.7, 4.0),
                                                                                ('Kiełki soczewicy', 119.0, 9.0, 0.6, 22.1),
                                                                                ('Kiełki soi', 141.0, 13.1, 6.7, 9.6),
                                                                                ('Kiwi', 56.0, 0.9, 0.5, 13.9),
                                                                                ('Kminek', 333.0, 20.0, 15.0, 50.0),
                                                                                ('Kolendra', 279.0, 22.0, 4.8, 52.0),
                                                                                ('Komosa ryżowa - quinoa', 334.0, 14.8, 5.0, 58.5),
                                                                                ('Komosa ryżowa - Quinoa', 334.0, 15.0, 5.0, 58.0),
                                                                                ('Koncentrat pomidorowy 30%', 92.0, 5.6, 1.5, 16.7),
                                                                                ('Koperek', 26.0, 2.8, 0.4, 6.1),
                                                                                ('Kostka rosołowa Rosół z kury z pietruszką i lubczykiem', 300.0, 10.0, 20.0, 10.0),
                                                                                ('Krewetka tygrysia', 92.0, 22.0, 0.0, 1.0),
                                                                                ('Kukurydza kolba', 110.0, 3.7, 1.5, 23.4),
                                                                                ('Kukurydza konserwowa', 102.0, 2.9, 1.2, 23.6),
                                                                                ('Kumin (kmin rzymski)', 429.0, 17.0, 22.0, 34.0),
                                                                                ('Kurki', 32.0, 1.5, 0.5, 6.9),
                                                                                ('Kurkuma', 354.0, 7.8, 9.9, 65.0),
                                                                                ('Len mielony', 253.0, 40.0, 9.0, 3.0),
                                                                                ('Len w nasionach', 500.0, 24.5, 31.0, 35.0),
                                                                                ('Limonka', 30.0, 0.7, 0.2, 10.5),
                                                                                ('Liście mięty', 77.0, 3.8, 0.9, 15.0),
                                                                                ('Liść laurowy', 313.0, 7.6, 8.4, 75.0),
                                                                                ('Łosoś smażony', 380.0, 21.2, 31.4, 4.0),
                                                                                ('Łosoś świeży', 201.0, 19.9, 13.6, 0.0),
                                                                                ('Łosoś wędzony', 162.0, 21.5, 8.4, 0.0),
                                                                                ('Magii', 17.0, 2.7, 0.0, 1.5),
                                                                                ('Majeranek', 271.0, 13.0, 7.0, 61.0),
                                                                                ('Majonez', 714.0, 1.3, 79.0, 2.6),
                                                                                ('Mak', 478.0, 20.1, 42.9, 24.7),
                                                                                ('Mąka kukurydziana', 337.0, 5.9, 3.0, 78.0),
                                                                                ('Mąka pszenna typ 1850', 309.0, 11.9, 2.3, 70.0),
                                                                                ('Mąka pszenna typ 500', 343.0, 10.1, 1.2, 74.0),
                                                                                ('Mąka pszenna typ 550', 344.0, 10.5, 1.6, 73.0),
                                                                                ('Mąka pszenna typ 750', 341.0, 11.6, 1.8, 71.3),
                                                                                ('Makaron bezjajeczny', 364.0, 11.0, 1.6, 77.6),
                                                                                ('Makaron czterojajeczny', 391.0, 13.2, 3.4, 78.3),
                                                                                ('Makaron dwujajeczny', 373.0, 12.0, 2.6, 76.8),
                                                                                ('Makaron farfalline pełnoziarnisty z 5 zbóż', 351.0, 14.4, 2.5, 63.8),
                                                                                ('Makaron penne pełnoziarnisty', 345.0, 15.2, 1.3, 68.0),
                                                                                ('Makaron rurki (z pszenicy Durum)', 350.0, 12.0, 1.5, 72.1),
                                                                                ('Makaron ryżowy', 356.0, 6.8, 0.7, 83.0),
                                                                                ('Makaron spaghetti razowy', 354.0, 13.0, 2.5, 66.5),
                                                                                ('Mąka ryżowa', 348.0, 7.2, 0.7, 79.2),
                                                                                ('Mąka żytnia typ 1400', 310.0, 7.1, 2.2, 75.3),
                                                                                ('Mąka żytnia typ 2000', 301.0, 8.1, 2.2, 74.0),
                                                                                ('Mąka żytnia typ 580', 330.0, 5.1, 1.5, 78.5),
                                                                                ('Mąka żytnia typ 720', 327.0, 5.9, 1.7, 77.4),
                                                                                ('Makrela świeża', 181.0, 18.7, 11.9, 0.0),
                                                                                ('Makrela wędzona', 221.0, 20.7, 15.5, 0.0),
                                                                                ('Maliny', 29.0, 1.3, 0.3, 12.0),
                                                                                ('Mandarynki', 42.0, 0.6, 0.2, 11.2),
                                                                                ('Mango', 67.0, 0.5, 0.3, 17.0),
                                                                                ('Marchewka', 27.0, 1.0, 0.2, 8.7),
                                                                                ('Marchewka z groszkiem, mrożonka', 39.0, 2.6, 0.3, 10.4),
                                                                                ('Marchewki mini', 41.0, 1.0, 0.0, 9.0),
                                                                                ('Maślanka 0,5 %', 37.0, 3.4, 0.5, 4.7),
                                                                                ('Masło ekstra', 735.0, 0.7, 82.5, 0.7),
                                                                                ('Masło klarowane', 883.0, 0.0, 99.0, 0.0),
                                                                                ('Masło orzechowe', 634.0, 26.6, 53.0, 8.5),
                                                                                ('Masło śmietankowe', 659.0, 1.1, 73.5, 1.1),
                                                                                ('Melon', 36.0, 0.9, 0.3, 8.4),
                                                                                ('Mieszanka mąk gryczanej, ryżowej lub owsianej', 351.0, 11.7, 2.7, 70.7),
                                                                                ('Mieszanka warzywna z kurczakiem, ryżem i grzybami chińskimi, mrożonka', 87.0, 4.3, 2.4, 13.3),
                                                                                ('Mieszanka ziół', 1.0, 0.0, 0.1, 0.0),
                                                                                ('Mięta pieprzowa', 77.0, 3.8, 0.9, 15.0),
                                                                                ('Migdały', 572.0, 20.0, 52.0, 20.5),
                                                                                ('Miks ulubionych warzwy', 38.0, 1.9, 0.3, 8.8),
                                                                                ('Mintaj świeży', 73.0, 16.6, 0.6, 0.0),
                                                                                ('Miód pszczeli', 324.0, 0.3, 0.0, 79.5),
                                                                                ('Mleko kokosowe w puszce', 203.0, 2.1, 18.0, 8.1),
                                                                                ('Mleko kozie 2%', 68.0, 3.2, 4.1, 4.5),
                                                                                ('Mleko owcze', 107.0, 6.0, 7.0, 5.1),
                                                                                ('Mleko sojowe', 41.0, 6.0, 1.4, 4.3),
                                                                                ('Mleko spożywcze 2,0%', 51.0, 3.4, 2.0, 4.9),
                                                                                ('Mleko w proszku pełne', 479.0, 27.0, 24.0, 38.7),
                                                                                ('Mleko zagęszczone niesłodzone', 131.0, 6.6, 7.5, 9.4),
                                                                                ('Mleko zagęszczone słodzone', 326.0, 7.5, 8.0, 55.3),
                                                                                ('Młody jęczmień proszek', 320.0, 52.0, 2.0, 21.0),
                                                                                ('Morele', 47.0, 0.9, 0.2, 11.9),
                                                                                ('Morele suszone', 284.0, 5.4, 1.2, 72.2),
                                                                                ('Morszczuk świeży', 89.0, 17.2, 2.2, 0.0),
                                                                                ('Mus jabłkowy', 124.0, 2.2, 0.2, 28.7),
                                                                                ('Musli z orzechami i  rodzynkami', 375.0, 11.5, 12.7, 62.9),
                                                                                ('Musli z suszonymi owocami', 325.0, 8.4, 3.4, 72.2),
                                                                                ('Musztarda', 162.0, 5.7, 6.4, 22.0),
                                                                                ('Napój kokosowy w kartonie', 30.0, 0.1, 2.0, 3.5),
                                                                                ('Nasiona Chia', 490.0, 16.0, 31.0, 44.0),
                                                                                ('Natka pietruszki', 41.0, 4.4, 0.4, 9.0),
                                                                                ('Nektarynka', 48.0, 0.9, 0.2, 11.8),
                                                                                ('Ocet balsamiczny', 116.0, 0.0, 0.0, 0.7),
                                                                                ('Ocet jabłkowy', 24.0, 0.0, 0.0, 6.0),
                                                                                ('Ocet winny', 20.0, 0.0, 0.0, 5.0),
                                                                                ('Ogórek', 13.0, 0.7, 0.1, 2.9),
                                                                                ('Ogórek kiszony', 11.0, 1.0, 0.1, 1.9),
                                                                                ('Ogórek konserwowy', 23.0, 0.4, 0.1, 4.9),
                                                                                ('Ogórek kwaszony', 11.0, 1.0, 0.1, 1.9),
                                                                                ('Ogórki konserwowe', 24.0, 0.3, 0.1, 5.6),
                                                                                ('Olej kokosowy', 900.0, 0.0, 100.0, 0.0),
                                                                                ('Olej rzepakowy', 884.0, 0.0, 100.0, 0.0),
                                                                                ('Olej słonecznikowy', 884.0, 0.0, 100.0, 0.0),
                                                                                ('Oliwa z oliwek', 882.0, 0.0, 99.6, 0.2),
                                                                                ('Oliwki czarne', 125.0, 1.4, 12.7, 4.1),
                                                                                ('Oliwki zielone marynowane', 125.0, 1.4, 12.7, 4.1),
                                                                                ('Oregano', 265.0, 9.0, 4.3, 69.0),
                                                                                ('Orzechy arachidowe', 560.0, 25.7, 46.1, 19.2),
                                                                                ('Orzechy brazylijskie', 656.0, 14.0, 66.0, 4.0),
                                                                                ('Orzechy laskowe', 640.0, 14.4, 63.0, 14.9),
                                                                                ('Orzechy piniowe', 673.0, 16.7, 68.4, 13.0),
                                                                                ('Orzechy pistacjowe', 589.0, 20.5, 48.5, 25.0),
                                                                                ('Orzechy włoskie', 645.0, 16.0, 60.3, 18.0),
                                                                                ('Orzechy ziemne', 603.0, 26.0, 50.0, 14.0),
                                                                                ('Ostra papryka', 0.4, 0.0, 0.0, 0.1),
                                                                                ('Otręby pszenne', 185.0, 16.0, 4.6, 61.9),
                                                                                ('Paluszek krabowy', 113.0, 6.5, 2.2, 16.8),
                                                                                ('Papaja', 41.0, 0.6, 0.1, 11.1),
                                                                                ('Papryka czerwona', 28.0, 1.3, 0.5, 6.6),
                                                                                ('Papryka czerwona konserwowa', 30.0, 0.8, 1.5, 5.0),
                                                                                ('Papryka sucha', 289.0, 15.0, 13.0, 56.0),
                                                                                ('Papryka zielona', 18.0, 1.1, 0.3, 4.6),
                                                                                ('Pasternak', 57.0, 1.6, 0.6, 15.5),
                                                                                ('Pasztet pieczony', 390.0, 17.0, 31.2, 13.5),
                                                                                ('Pasztet podlaski z kurczaka', 228.0, 6.7, 21.1, 3.6),
                                                                                ('Pasztet z kurczaka', 214.0, 14.4, 14.3, 7.5),
                                                                                ('Pestki dyni', 556.0, 24.5, 45.8, 18.0),
                                                                                ('Pestki słonecznika', 561.0, 24.4, 43.7, 24.6),
                                                                                ('Pesto', 340.0, 3.7, 34.6, 6.3),
                                                                                ('Pieczarki', 17.0, 2.7, 0.4, 2.6),
                                                                                ('Pieczarki marynowane konserwowe', 19.0, 2.3, 0.4, 4.3),
                                                                                ('Pieczeń wołowa', 117.0, 20.9, 3.6, 0.0),
                                                                                ('Pieczona polędwica wołowa', 168.0, 19.7, 9.9, 0.0),
                                                                                ('Pieczywo tostowe', 305.0, 8.1, 4.7, 58.8),
                                                                                ('Pieczywo tostowe grahamowe', 273.0, 7.5, 4.2, 53.8),
                                                                                ('Pieczywo Wasa', 370.0, 10.0, 3.0, 70.0),
                                                                                ('Pieprz biały', 296.0, 10.0, 2.1, 69.0),
                                                                                ('Pieprz czarny', 318.0, 11.0, 3.3, 65.0),
                                                                                ('Pieprz czerwony', 318.0, 12.0, 17.0, 57.0),
                                                                                ('Pierś indyka bez skóry', 84.0, 19.2, 0.7, 0.0),
                                                                                ('Pierś indyka ze skórą', 100.0, 18.7, 2.7, 0.0),
                                                                                ('Pierś kurczaka bez skóry', 99.0, 21.5, 1.3, 0.0),
                                                                                ('Pietruszka', 38.0, 2.6, 0.5, 10.5),
                                                                                ('Pikle konserwowe', 62.0, 1.3, 0.2, 15.5),
                                                                                ('Płatki jaglane', 361.0, 10.0, 4.0, 69.0),
                                                                                ('Płatki jęczmienne', 355.0, 9.8, 3.6, 79.4),
                                                                                ('Płatki kukurydziane', 363.0, 6.9, 2.5, 83.6),
                                                                                ('Płatki migdałowe', 581.0, 22.0, 51.0, 10.0),
                                                                                ('Płatki owsiane', 366.0, 11.9, 7.2, 69.3),
                                                                                ('Płatki pszenne', 351.0, 9.0, 3.0, 81.0),
                                                                                ('Płatki ryżowe', 344.0, 6.7, 0.7, 78.9),
                                                                                ('Płatki żytnie', 343.0, 6.4, 3.2, 82.6),
                                                                                ('Podudzie indyka bez skóry', 100.0, 16.6, 3.7, 0.0),
                                                                                ('Polędwica łososiowa', 106.0, 20.0, 2.0, 2.0),
                                                                                ('Polędwica luksusowa', 177.0, 19.5, 10.0, 2.4),
                                                                                ('Polędwica sopocka', 165.0, 19.9, 9.1, 0.9),
                                                                                ('Polędwica wołowa', 113.0, 20.1, 3.5, 0.0),
                                                                                ('Polędwica z indyka', 105.0, 15.8, 4.6, 0.1),
                                                                                ('Polędwica z piersi kurczaka', 93.0, 20.4, 1.2, 0.0),
                                                                                ('Pomarańcza', 44.0, 0.9, 0.2, 11.3),
                                                                                ('Pomidor', 15.0, 0.9, 0.2, 3.6),
                                                                                ('Pomidory koktajlowe', 15.0, 0.9, 0.2, 3.6),
                                                                                ('Pomidory z puszki', 23.0, 1.3, 0.2, 4.0),
                                                                                ('Por', 24.0, 2.2, 0.3, 5.7),
                                                                                ('Porzeczki białe', 33.0, 1.0, 0.2, 13.1),
                                                                                ('Porzeczki czarne', 35.0, 1.3, 0.2, 14.9),
                                                                                ('Porzeczki czerwone', 31.0, 1.1, 0.2, 13.8),
                                                                                ('Powidła śliwkowe', 214.0, 1.0, 0.2, 53.0),
                                                                                ('Poziomki', 33.0, 0.8, 0.5, 8.3),
                                                                                ('Proszek do pieczenia', 97.0, 0.1, 0.4, 47.0),
                                                                                ('Przecier pomidorowy', 25.0, 1.2, 0.1, 4.5),
                                                                                ('Przyprawa do drobiu', 307.0, 9.6, 7.5, 66.0),
                                                                                ('Przyprawa do ryb', 307.0, 9.6, 7.5, 66.0),
                                                                                ('Przyprawa "Jarzynka"', 90.0, 1.9, 0.4, 23.3),
                                                                                ('Pstrąg strumieniowy świeży', 97.0, 19.2, 2.1, 0.0),
                                                                                ('Pstrąg tęczowy świeży', 160.0, 18.6, 9.6, 0.0),
                                                                                ('Pstrąg wędzony', 117.0, 19.4, 4.4, 0.2),
                                                                                ('Pumpernikiel', 240.0, 5.9, 2.0, 58.2),
                                                                                ('Rabarbar', 9.0, 0.5, 0.1, 4.6),
                                                                                ('Rodzynki suszone', 277.0, 2.3, 0.5, 71.2),
                                                                                ('Rostbef wołowy', 152.0, 21.5, 7.3, 0.0),
                                                                                ('Rozmaryn', 331.0, 4.9, 15.0, 64.0),
                                                                                ('Rukola', 25.0, 2.6, 0.7, 3.7),
                                                                                ('Ryż biały', 344.0, 6.7, 0.7, 78.9),
                                                                                ('Ryż brązowy', 322.0, 7.1, 1.9, 76.8),
                                                                                ('Rzepa', 26.0, 1.1, 0.3, 8.2),
                                                                                ('Rzeżucha', 32.0, 2.6, 0.7, 5.5),
                                                                                ('Rzodkiewka', 14.0, 1.0, 0.2, 4.4),
                                                                                ('Salami', 540.0, 21.9, 50.6, 0.9),
                                                                                ('Salami popularne', 568.0, 21.6, 53.7, 1.4),
                                                                                ('Salami z pieprzem', 405.0, 17.0, 37.0, 1.0),
                                                                                ('Sałata', 14.0, 1.4, 0.2, 2.9),
                                                                                ('Sałata lodowa', 14.0, 0.9, 0.1, 3.0),
                                                                                ('Sałata rzymska', 17.0, 1.2, 0.0, 3.0),
                                                                                ('Sandacz świeży', 84.0, 19.2, 0.7, 0.0),
                                                                                ('Sardynki w oleju', 221.0, 24.1, 13.9, 0.0),
                                                                                ('Sardynki w pomidorach', 162.0, 17.0, 9.9, 1.4),
                                                                                ('Schab pieczony', 291.0, 30.4, 18.7, 0.7),
                                                                                ('Seler konserwowy', 17.0, 0.7, 0.1, 5.4),
                                                                                ('Seler korzeniowy', 21.0, 1.6, 0.3, 7.7),
                                                                                ('Seler naciowy', 13.0, 1.0, 0.2, 3.6),
                                                                                ('Ser Brie pełnotłusty', 329.0, 19.8, 28.0, 0.2),
                                                                                ('Ser Camembert pełnotłusty', 291.0, 21.4, 23.0, 0.2),
                                                                                ('Ser Cheddar pełnotłusty', 391.0, 27.1, 31.7, 0.1),
                                                                                ('Ser Edamski pełnotłusty', 313.0, 26.1, 23.4, 0.1),
                                                                                ('Kurczak z ryżem i warzywami', 130.0, 11.0, 3.5, 14.0),
                                                                                ('Gulasz wołowy z kaszą gryczaną', 140.0, 10.0, 6.0, 12.0),
                                                                                ('Łosoś pieczony z ziemniakami', 160.0, 14.0, 9.0, 8.0),
                                                                                ('Pierogi ruskie', 180.0, 6.0, 5.0, 25.0),
                                                                                ('Gołąbki z mięsem i ryżem', 135.0, 7.0, 6.0, 13.0),
                                                                                ('Kotlety mielone z ziemniakami', 185.0, 11.0, 10.0, 12.0),
                                                                                ('Spaghetti bolognese', 150.0, 8.0, 4.5, 18.0),
                                                                                ('Makaron z kurczakiem i szpinakiem', 140.0, 10.0, 4.0, 15.0),
                                                                                ('Schabowy z ziemniakami i mizerią', 190.0, 12.0, 11.0, 13.0),
                                                                                ('Bigos tradycyjny', 110.0, 6.0, 6.0, 6.0),
                                                                                ('Placki ziemniaczane z gulaszem', 170.0, 7.0, 8.0, 18.0),
                                                                                ('Kurczak curry z ryżem', 145.0, 12.0, 5.0, 14.0),
                                                                                ('Zupa pomidorowa z ryżem', 50.0, 1.5, 1.0, 8.0),
                                                                                ('Zupa ogórkowa z ziemniakami', 60.0, 2.0, 1.5, 9.0),
                                                                                ('Ryż z warzywami i tofu', 130.0, 5.0, 4.0, 18.0),
                                                                                ('Kluski śląskie z sosem pieczeniowym', 160.0, 6.0, 5.0, 22.0),
                                                                                ('Sałatka gyros z kurczakiem', 120.0, 9.0, 7.0, 6.0),
                                                                                ('Kopytka z masłem i bułką tartą', 170.0, 5.0, 6.0, 26.0),
                                                                                ('Zapiekanka ziemniaczana z serem', 180.0, 7.0, 8.0, 19.0),
                                                                                ('Naleśniki z mięsem i sosem pomidorowym', 155.0, 8.0, 6.0, 17.0),
                                                                                ('Serek homogenizowany', 161.0, 12.7, 11.0, 3.0),
                                                                                ('Serek homogenizowany waniliowy', 159.0, 16.8, 4.2, 13.3),
                                                                                ('Serek twarogowy ziarnisty', 101.0, 12.3, 4.3, 3.3),
                                                                                ('Serek typu "Fromage" naturalny', 379.0, 10.2, 37.1, 2.4),
                                                                                ('Ser Ementaler pełnotłusty', 380.0, 28.8, 29.7, 0.1),
                                                                                ('Ser Gouda pełnotłusty', 316.0, 27.9, 22.9, 0.1),
                                                                                ('Ser kozi', 388.0, 21.4, 33.9, 0.0),
                                                                                ('Ser kozi, twarożek', 168.0, 8.7, 14.0, 4.0),
                                                                                ('Ser Mascarpone', 394.0, 3.5, 40.0, 5.1),
                                                                                ('Ser mozzarella', 254.0, 24.0, 16.0, 3.0),
                                                                                ('Ser mozzarella light', 157.0, 19.0, 8.5, 1.0),
                                                                                ('Ser Parmezan', 452.0, 41.5, 32.0, 0.1),
                                                                                ('Ser Radamer', 339.0, 26.2, 26.0, 0.1),
                                                                                ('Ser Rokpol pełnotłusty', 363.0, 22.6, 30.6, 0.1),
                                                                                ('Ser Salami pełnotłusty', 351.0, 25.2, 28.1, 0.1),
                                                                                ('Ser topiony', 298.0, 13.5, 27.0, 1.2),
                                                                                ('Ser Trapistów pełnotłusty', 367.0, 23.5, 30.7, 0.1),
                                                                                ('Ser Trapistów tłusty', 351.0, 28.0, 26.8, 0.1),
                                                                                ('Ser twarogowy chudy', 99.0, 19.8, 0.5, 3.5),
                                                                                ('Ser twarogowy półtłusty', 133.0, 18.7, 4.7, 3.7),
                                                                                ('Ser twarogowy tłusty', 175.0, 17.7, 10.1, 3.5),
                                                                                ('Ser Tylżycki pełnotłusty', 353.0, 26.1, 27.9, 0.1),
                                                                                ('Ser typu "Feta"', 215.0, 17.0, 16.0, 1.0),
                                                                                ('Sezam', 632.0, 23.2, 59.9, 10.0),
                                                                                ('Siemie lniane', 534.0, 18.0, 42.0, 29.0),
                                                                                ('Skórka cytrynowa', 120.0, 1.6, 0.2, 25.0),
                                                                                ('Skrobia kukurydziana', 353.0, 0.2, 0.0, 88.5),
                                                                                ('Skrobia ziemniaczana', 343.0, 0.6, 0.1, 83.9),
                                                                                ('Śledź solony', 217.0, 19.8, 15.4, 0.0),
                                                                                ('Śledź w oleju', 301.0, 16.4, 26.5, 0.0),
                                                                                ('Śliwka', 45.0, 0.6, 0.2, 11.7),
                                                                                ('Śliwki suszone', 267.0, 3.5, 1.2, 68.9),
                                                                                ('Słodki ziemniak (batat)', 86.0, 1.6, 0.1, 20.0),
                                                                                ('Śmietana, 12% tłuszczu', 133.0, 2.7, 12.0, 3.9),
                                                                                ('Śmietana, 18% tłuszczu', 184.0, 2.5, 18.0, 3.6),
                                                                                ('Śmietanka kremowa 30%', 287.0, 2.2, 30.0, 3.1),
                                                                                ('Soczewica czerwona suche nasiona', 327.0, 25.4, 3.0, 57.5),
                                                                                ('Soja suche nasiona', 382.0, 34.3, 19.6, 32.7),
                                                                                ('Sok ananasowy', 48.0, 0.3, 0.1, 11.4),
                                                                                ('Sok brzoskwiniowo pomarańczowy', 32.0, 0.7, 0.1, 7.4),
                                                                                ('Sok buraczany', 34.0, 0.8, 0.2, 7.6),
                                                                                ('Sok cytrynowy', 30.0, 0.4, 0.3, 6.4),
                                                                                ('Sok egzotyczny', 57.0, 0.8, 0.3, 12.7),
                                                                                ('Sok grejpfrutowy', 40.0, 0.5, 0.1, 9.2),
                                                                                ('Sok jabłkowy', 42.0, 0.1, 0.1, 10.0),
                                                                                ('Sok marchwiowo brzoskwiniowy', 44.0, 0.5, 0.1, 11.3),
                                                                                ('Sok marchwiowo jabłkowo bananowy', 39.0, 0.3, 0.1, 10.2),
                                                                                ('Sok marchwiowo jabłkowo śliwkowy', 39.0, 0.4, 0.2, 10.2),
                                                                                ('Sok marchwiowo jabłkowy', 44.0, 0.5, 0.2, 12.1),
                                                                                ('Sok marchwiowo pomarańczowy', 40.0, 0.6, 0.1, 10.8),
                                                                                ('Sok marchwiowy', 43.0, 0.4, 0.1, 11.3),
                                                                                ('Sok pomarańczowo grejpfrutowy', 43.0, 0.6, 0.1, 9.8),
                                                                                ('Sok pomarańczowy', 43.0, 0.6, 0.1, 9.9),
                                                                                ('Sok pomidorowy', 14.0, 0.8, 0.2, 3.3),
                                                                                ('Sok wieloowocowy', 45.0, 0.2, 0.1, 10.9),
                                                                                ('Sok wielowarzywny', 25.0, 1.0, 0.3, 5.7),
                                                                                ('Sól', 0.0, 0.0, 0.0, 0.0),
                                                                                ('Sola świeża', 83.0, 17.5, 1.4, 0.0),
                                                                                ('Sól czosnkowa', 9.0, 4.3, 1.2, 1.9),
                                                                                ('Sos sojowy', 0.0, 0.6, 0.0, 0.3),
                                                                                ('Starta skórka z pomarańczy', 120.0, 1.6, 0.2, 25.0),
                                                                                ('Suszone pomidory', 215.0, 5.0, 14.0, 23.0),
                                                                                ('Syrop klonowy', 265.0, 0.1, 0.1, 63.0),
                                                                                ('Szafran', 310.0, 11.0, 5.9, 65.0),
                                                                                ('Szałwia', 315.0, 11.0, 13.0, 61.0),
                                                                                ('Szczaw', 21.0, 1.1, 0.8, 4.9),
                                                                                ('Szczupak świeży', 82.0, 18.4, 0.8, 0.0),
                                                                                ('Szczypiorek', 29.0, 4.1, 0.8, 3.9),
                                                                                ('Szparagi', 18.0, 1.9, 0.2, 3.7),
                                                                                ('Szpinak', 16.0, 2.6, 0.4, 3.0),
                                                                                ('Szpinak, mrożonka', 15.0, 2.3, 0.4, 2.7),
                                                                                ('Szponder wołowy', 217.0, 19.3, 15.7, 0.0),
                                                                                ('Szprotka wędzona', 243.0, 19.3, 18.3, 0.0),
                                                                                ('Szynka delikatesowa z kurczaka', 123.0, 18.2, 5.6, 0.0),
                                                                                ('Szynka kanapkowa', 102.0, 14.2, 4.4, 1.4),
                                                                                ('Szynka parmeńska', 135.0, 26.0, 3.0, 1.0),
                                                                                ('Szynka wiejska', 253.0, 17.1, 20.3, 0.9),
                                                                                ('Szynka wieprzowa gotowana', 233.0, 16.4, 18.3, 1.0),
                                                                                ('Szynka wołowa gotowana', 107.0, 20.9, 2.0, 1.1),
                                                                                ('Szynka z indyka', 84.0, 17.1, 1.6, 0.1),
                                                                                ('Szynka z piersi kurczaka', 98.0, 21.2, 1.2, 0.2),
                                                                                ('Szynka z udźca kurczaka', 117.0, 17.2, 5.3, 0.0),
                                                                                ('Szynkówka wieprzowa', 191.0, 13.6, 14.7, 1.4),
                                                                                ('Szynkówka wołowa', 85.0, 16.2, 1.5, 1.4),
                                                                                ('Tofu', 112.0, 12.0, 6.0, 3.0),
                                                                                ('Truskawki', 28.0, 0.7, 0.4, 7.2),
                                                                                ('Tuńczyk w oleju', 190.0, 27.1, 9.0, 0.0),
                                                                                ('Tuńczyk w sosie własnym', 96.0, 21.0, 1.2, 0.0),
                                                                                ('Tymianek', 276.0, 9.1, 7.4, 64.0),
                                                                                ('Udko kurczaka bez skóry', 125.0, 17.8, 6.0, 0.0),
                                                                                ('Udko kurczaka ze skórą', 158.0, 16.8, 10.2, 0.0),
                                                                                ('Udziec indyka bez skóry', 104.0, 19.4, 2.8, 0.0),
                                                                                ('Udziec indyka ze skórą', 131.0, 18.4, 6.4, 0.0),
                                                                                ('Wafle ryżowe', 390.0, 8.0, 3.0, 81.0),
                                                                                ('Wątróbka kurczaka', 136.0, 19.1, 6.3, 0.6),
                                                                                ('Wędzona pierś z kurczaka', 107.0, 23.0, 0.5, 0.0),
                                                                                ('Wędzonka wołowa gotowana', 102.0, 17.8, 3.1, 0.5),
                                                                                ('Wieprzowina karkówka', 267.0, 16.1, 22.8, 0.0),
                                                                                ('Wieprzowina łopatka', 257.0, 16.0, 21.7, 0.0),
                                                                                ('Wieprzowina schab surowy', 174.0, 21.0, 10.0, 0.0),
                                                                                ('Wieprzowina żeberka', 321.0, 15.2, 29.3, 0.0),
                                                                                ('Wino białe półwytrawne', 81.0, 0.0, 0.0, 3.7),
                                                                                ('Wino białe słodkie', 95.0, 0.2, 0.0, 5.9),
                                                                                ('Wino białe wytrawne', 66.0, 0.1, 0.0, 0.6),
                                                                                ('Wino czerwone', 68.0, 0.1, 0.0, 0.2),
                                                                                ('Winogrona', 69.0, 0.5, 0.2, 17.6),
                                                                                ('Wiórki kokosowe', 606.0, 5.6, 63.2, 27.0),
                                                                                ('Wiśnie', 47.0, 0.9, 0.4, 10.9),
                                                                                ('Włoszczyzna krojona w paski', 25.0, 1.4, 0.3, 7.9),
                                                                                ('Woda', 0.0, 0.0, 0.0, 0.0),
                                                                                ('Zarodki pszenne', 323.0, 27.5, 9.4, 45.5),
                                                                                ('Żelatyna', 343.0, 84.2, 0.1, 0.0),
                                                                                ('Ziele angielskie', 263.0, 6.1, 8.7, 72.0),
                                                                                ('Ziemniaki', 77.0, 1.9, 0.1, 18.3),
                                                                                ('Ziemniaki młode', 69.0, 1.8, 0.1, 16.3),
                                                                                ('Zioła prowansalskie', 1.0, 0.0, 0.1, 0.0),
                                                                                ('Żółtko jajka kurzego', 314.0, 15.5, 28.2, 0.3),
                                                                                ('Żurawina niskosłodzona do mięs', 161.0, 0.2, 0.7, 38.8),
                                                                                ('Żurawina suszona', 320.0, 0.1, 1.4, 82.4);
        END IF;
    END $$;
