DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM exercise_videos LIMIT 1) THEN
            INSERT INTO exercise_videos
            (name, youtube_url)
            VALUES
                ('Martwy ciąg ze sztangą', 'https://www.youtube.com/watch?v=Z6gcRfPNcZo&t=1s'),
                ('Martwy ciąg z kettlebell', 'https://www.youtube.com/watch?v=LnIMaf-XOpM&t=1s'),
                ('Rumuński martwy ciąg z hantlami', 'https://www.youtube.com/watch?v=V8Hdl1FiNt4&t=1s'),
                ('Leżące uginanie nóg', 'https://www.youtube.com/watch?v=Dq5y4WEcqqo'),
                ('Uginanie ramion ze sztangą', 'https://www.youtube.com/watch?v=pQfJR-sSIvA'),
                ('Mostek biodrowy na podłodze', 'https://www.youtube.com/watch?v=Z3cY3d3BBo4'),
                ('Kobra na brzuchu', 'https://www.youtube.com/watch?v=keErJXdp2lE'),
                ('Skłony Good Mornings', 'https://www.youtube.com/watch?v=Daq-wJMUnes'),
                ('Deska boczna', 'https://www.youtube.com/watch?v=44ND4bOB-T0'),
                ('Deska', 'https://www.youtube.com/watch?v=mwlp75MS6Rg'),
                ('Deska z chodzeniem', 'https://www.youtube.com/watch?v=6Tv4xTRPtUc'),
                ('Deska na prostych ramionach', 'https://www.youtube.com/watch?v=MDxfAuBbHHA'),
                ('Przysiad więzienny', 'https://www.youtube.com/watch?v=UYbsgiiZgao'),
                ('Wyskok z przysiadu', 'https://www.youtube.com/watch?v=tZSYZdtbONc'),
                ('Bułgarski przysiad', 'https://www.youtube.com/watch?v=hbw7hdyOpq0'),
                ('Przysiad z hantlem (Goblet Squat)', 'https://www.youtube.com/watch?v=nfX7IFK9UNI'),
                ('Przysiad z hantlami z przodu', 'https://www.youtube.com/watch?v=hZI8Yy5elZs'),
                ('Burpees', 'https://www.youtube.com/watch?v=Ny8JWqh4lNg'),
                ('Przysiad przedni z kettlebell', 'https://www.youtube.com/watch?v=-TeEMXoHQPM'),
                ('Bird Dog', 'https://www.youtube.com/watch?v=ZdAHe9_HeEw'),
                ('Podciąganie', 'https://www.youtube.com/watch?v=9yVGh3XbJ34'),
                ('Podciąganie z gumą', 'https://www.youtube.com/watch?v=B_VkNQS5YLs'),
                ('Rumuński martwy ciąg(sztanga)', 'https://www.youtube.com/watch?v=xgusDooVfKU'),
                ('Rosyjski twist', 'https://www.youtube.com/watch?v=s0kT80JLCfA'),
                ('Odwrotne spięcia brzucha z rotacją kolan', 'https://www.youtube.com/watch?v=wtKWBzDwfIM'),
                ('Pompka', 'https://www.youtube.com/watch?v=WDIpL0pjun0'),
                ('Pompka plyometryczna', 'https://www.youtube.com/watch?v=MH4gcTKQiEc'),
                ('Pompka pike', 'https://www.youtube.com/watch?v=2b5t0Cu2nQI'),
                ('Pompka odwrócona', 'https://www.youtube.com/watch?v=h45WmYKSJG0'),
                ('Pompka na ławce ujemnej', 'https://www.youtube.com/watch?v=DBz85WuXqMk'),
                ('Pompka na ławce dodatniej', 'https://www.youtube.com/watch?v=0JUrOH--Kdk'),
                ('Pompka Archer', 'https://www.youtube.com/watch?v=IDu6pRAPChg'),
                ('Zmodyfikowana pompka', 'https://www.youtube.com/watch?v=PDr5B2jLUOw'),
                ('Wspięcia na palce na suwnicy', 'https://www.youtube.com/watch?v=8k435cj30gc'),
                ('Pajacyki', 'https://www.youtube.com/watch?v=uLVt6u15L98'),
                ('Suwnica', 'https://www.youtube.com/watch?v=cDGOn-yfKJA'),
                ('Suwnica jednonóż', 'https://www.youtube.com/watch?v=3aYsOsBA7ZE'),
                ('Skoki na skrzynię', 'https://www.youtube.com/watch?v=DXu-8TAJwi4'),
                ('Krzyż żelazny', 'https://www.youtube.com/watch?v=uBEXsoMclPY&t=1s'),
                ('Uginanie ramion z kettlebell z przysiadem', 'https://www.youtube.com/watch?v=BPGOyQKy9R0'),
                ('Face Pull', 'https://www.youtube.com/watch?v=eTCBSFlCJ_s'),
                ('Rozpiętki na wyciągu', 'https://www.youtube.com/watch?v=XY6JrX1wyxk'),
                ('Wiosłowanie gumą stojąc', 'https://www.youtube.com/watch?v=qykwviNOIyc'),
                ('Wyciskanie wąskim chwytem na ławce', 'https://www.youtube.com/watch?v=LJeqLAmJLfs'),
                ('Dead Bug', 'https://www.youtube.com/watch?v=bxn9FBrt4-A'),
                ('Wyskoki w wykroku', 'https://www.youtube.com/watch?v=_5kDxC0flg0'),
                ('Siedzące wiosłowanie blisko', 'https://www.youtube.com/watch?v=k0cTJCfxa0Y'),
                ('Pozycja dziecka', 'https://www.youtube.com/watch?v=_ZX_zTOBgp8'),
                ('Wyskoki tuck jump', 'https://www.youtube.com/watch?v=-bnJGikRGsM'),
                ('Rozpiętki kablowe stojąc', 'https://www.youtube.com/watch?v=XNf6TBErGys'),
                ('Dipy na ławce', 'https://www.youtube.com/watch?v=WVeZDBhZwLA'),
                ('Wyciskanie maszynowe', 'https://www.youtube.com/watch?v=lRo9zZ7EwpM'),
                ('Wyciskanie hantlem jednorącz', 'https://www.youtube.com/watch?v=qFTnmyC-nf4'),
                ('Wyciskanie hantlami z gumą', 'https://www.youtube.com/watch?v=_x5m-s8xTf0'),
                ('Wyciskanie hantlem jednorącz na skosie', 'https://www.youtube.com/watch?v=iJ-GwVeUuCg'),
                ('Wyciskanie hantlami na skosie', 'https://www.youtube.com/watch?v=JKnpHchOWPU'),
                ('Leżące uginanie nóg: dwie nogi faza koncentryczna jedna ekscentryczna', 'https://www.youtube.com/watch?v=_7sVQlruVZc'),
                ('Leżące uginanie nóg: jedna noga', 'https://www.youtube.com/watch?v=kGIfh3hHY0w'),
                ('Siedzące uginanie nóg', 'https://www.youtube.com/watch?v=_2Kd0d-JEUM'),
                ('Siedzące uginanie nóg jednonóż', 'https://www.youtube.com/watch?v=PXNJ71rksvU'),
                ('Przysiad jednonóż', 'https://www.youtube.com/watch?v=sSXnaFyhiZs'),
                ('Przysiad jednonóż z dotknięciem', 'https://www.youtube.com/watch?v=h6lET2_DLA0'),
                ('Przysiad jednonóż do wiosłowania', 'https://www.youtube.com/watch?v=LmGbrgGJS6E'),
                ('Wyciskanie sztangi na ławce', 'https://www.youtube.com/watch?v=CayG6UYqL8g'),
                ('Wyciskanie sztangi na ławce z gumą', 'https://www.youtube.com/watch?v=N4H4o8k9WbE'),
                ('Wyciskanie sztangi na ławce z łańcuchami', 'https://www.youtube.com/watch?v=6UKcYcDme-Y'),
                ('Wyciskanie sztangi na ławce skośnej', 'https://www.youtube.com/watch?v=BjGLs6KGWUc'),
                ('Wałkowanie pianą: Przywodziciele', 'https://www.youtube.com/watch?v=Nqol0T6rKDg'),
                ('Wałkowanie pianą: Łydki', 'https://www.youtube.com/watch?v=6f2LO5EeB0I'),
                ('Wałkowanie pianą: Mięsień najszerszy grzbietu', 'https://www.youtube.com/watch?v=5S2suclGl7o'),
                ('Statyczne: Rozciąganie motyla', 'https://www.youtube.com/watch?v=v4OLkxi5-Q0'),
                ('Statyczne: Rozciąganie mięśnia najszerszego piłką', 'https://www.youtube.com/watch?v=kEH6jatSVSw'),
                ('Rozciąganie łydek na siedząco', 'https://www.youtube.com/watch?v=83G00Fwlqqw'),
                ('Statyczne: Rozciąganie przywodzicieli na stojąco', 'https://www.youtube.com/watch?v=IzHUoWs0maQ'),
                ('Stanie na jednej nodze z wyciągnięciem do przodu', 'https://www.youtube.com/watch?v=UrB5wA7B3hI');
        END IF;
    END$$;